target-version = "py38"

[lint]
select = [
    "B",
    "C4",
    "COM",
    "E",
    "F", # Pyflakes
    "FLY", # flynt
    "I",
    "ISC",
    "PERF",
    "PL", # Pylint
    "RUF",
    "S", # Bandit
    "UP",
    "W",
]
# COM812: as recommended by ruff-format
ignore = ["COM812", "PLR0911", "PLR0912", "PLR0913", "PLR0915", "PLR2004", "E501", "RUF012", "S311", "PERF203"]
